// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	Email string `json:"email"`
	UUID  string `json:"UUID"`
}

type UserInput struct {
	Email string `json:"email"`
}

type Users struct {
	Count *int    `json:"count"`
	List  []*User `json:"list"`
}
