// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	Email     string  `json:"email"`
	UUID      string  `json:"uuid"`
	Firstname *string `json:"firstname"`
	Lastname  *string `json:"lastname"`
}

type UserInput struct {
	Email     *string `json:"email"`
	Firstname *string `json:"firstname"`
	Lastname  *string `json:"lastname"`
}

type Users struct {
	Count int     `json:"count"`
	List  []*User `json:"list"`
}
