server-host: 0.0.0.0
server-port: 8080
server-static-dir: ./ui/dist/client
gin-mode: debug
gql-path: /gql
gql-playground-path: /playground
gql-playground-enabled: true
gorm-dialect: sqlite3
gorm-conn-dsn: sqlite3.db
gorm-seed-db: true
gorm-log-mode: true
gorm-auto-migrate: true
